local street = display.newImage( "Street.png" )
street.x = 512; street.y = 184
street.width = 1024; street.height = 768
local foreground = display.newImage( "Car.png" )
foreground.x = 512; foreground.y = 384
foreground.width = 1024; foreground.height = 768
local brake = display.newImage( "Pedal.png" )
brake.x = 360; brake.y = 584
local gas = display.newImage( "Pedal.png" )
gas.x = 660; gas.y = 584
local car = display.newImage( "FullCar.png" )